USE ROGIL
GO

-----CREACION DE TABLAS CON PK

CREATE TABLE USUARIOS (
CODIGO_USUARIO int NOT NULL IDENTITY (1, 1) PRIMARY KEY,
USUARIO varchar(255) NOT NULL,
CLAVE varchar(255) NOT NULL,
NOMBRE_USUARIO varchar(255) NOT NULL,
FECHA_REGISTRO datetime NOT NULL,
CODIGO_PERFIL int NOT NULL
);  


---- TABLA PERFIL USUARIO

CREATE TABLE PERFIL (
CODIGO_PERFIL int NOT NULL IDENTITY (1,1) PRIMARY KEY,
DESCRIPCION VARCHAR (25)
);

CREATE TABLE PRODUCTOS (
    CODIGO_PRODUCTO int NOT NULL IDENTITY (1,1) PRIMARY KEY,
    NOMBRE_PRODUCTO varchar (255) NOT NULL,
    ID_FABRICANTE int NOT NULL,
    FECH_VENCIMIENTO datetime NOT NULL,
    PRECIO numeric(19,4),
    STOCK numeric(19,4),
);

CREATE TABLE PROVEEDORES (
    CODIGO_PROVEEDOR int NOT NULL IDENTITY (1,1) PRIMARY KEY,
    NOMBRE_PROVEEDOR varchar(255) NOT NULL
);

CREATE TABLE KARDEX (
    CODIGO_KARDEX int NOT NULL IDENTITY (1,1) PRIMARY KEY,
    ID_PRODUCTO int NOT NULL,
    TIPO_TRANSACCION varchar (255),
    CANTIDAD int NOT NULL,
    FECHA datetime NOT NULL
);

CREATE TABLE LIQUIDACION (
    CODIGO_LIQUIDACION int NOT NULL IDENTITY (1,1) PRIMARY KEY,
    ID_PRODUCTO int NOT NULL,
    CANTIDAD int NOT NULL,
    FECH_LIQUIDACION datetime NOT NULL,
    ID_PROVEEDOR int NOT NULL 
);

----------------Llaves Foraneasq
