USE ROGIL
GO

-----CREACION DE TABLAS CON PK
--Tabla de Creacion de usuario de empleados

CREATE TABLE USUARIOS (
CODIGO_USUARIO int NOT NULL IDENTITY (1, 1) PRIMARY KEY,
USUARIO varchar(255) NOT NULL,
NOMBRE varchar(255) NOT NULL,
APELLIDO varchar(255) NOT NULL,
CLAVE varchar(255) NOT NULL,
FECHA_REGISTRO datetime NOT NULL,
ID_PERFIL int NOT NULL,
FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(CODIGO_PERFIL)
);  

---- TABLA PERFIL USUARIO
CREATE TABLE PERFIL (
CODIGO_PERFIL int NOT NULL IDENTITY (1,1) PRIMARY KEY,
DESCRIPCION varchar (50)
);
--------------------------------------------------------------

CREATE TABLE PROVEEDORES (
    CODIGO_PROVEEDOR int NOT NULL IDENTITY (1,1) PRIMARY KEY,
    NOMBRE_PROVEEDOR varchar(255) NOT NULL,
    TELEFONO varchar(10) NOT NULL,
    DIRECCION varchar(255),
    CORREO varchar (255),
);

CREATE TABLE TIPO_PRODUCTO (
    CODIGO_TPRODUCTO int NOT NULL IDENTITY(1,1) PRIMARY KEY,
    TIP varchar(255) NOT NULL,
    DESCRIPCION text
);

CREATE TABLE LABORATORIO(
    CODIGO_LABORATORIO int NOT NULL IDENTITY(1,1) PRIMARY KEY,
    NOMBRE varchar(100)
);

CREATE TABLE PRODUCTOS (
    CODIGO_PRODUCTO int NOT NULL IDENTITY (1,1) PRIMARY KEY,
    NOMBRE_PRODUCTO varchar (255) NOT NULL,
    DESCRIPCION text,
    COSTO numeric(15,4) NOT NULL,  
    PRECIO_VENTA numeric(15,4),
    ID_TIPO_PRODUCTO int NOT NULL,
    ID_LABORATORIO int NOT NULL,
    FOREIGN KEY (ID_TIPO_PRODUCTO) REFERENCES TIPO_PRODUCTO(CODIGO_TPRODUCTO),
    FOREIGN KEY (ID_LABORATORIO) REFERENCES LABORATORIO(CODIGO_LABORATORIO)
);

CREATE TABLE LOTES_INVENTARIO (
    CODIGO_LOTE int NOT NULL IDENTITY (1,1) PRIMARY KEY,
    UNID_ENTRANTES int NOT NULL,
    VENCIMIENTO datetime NOT NULL,
    ID_PRODUCTO int NOT NULL,
    ID_PROVEEDOR int NOT NULL,
    COMENTARIO Text,
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(CODIGO_PRODUCTO),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(CODIGO_PROVEEDOR) 
);

CREATE TABLE VENTA(
    CODIGO_VENTA int NOT NULL IDENTITY(1,1) PRIMARY KEY,
    FECHA datetime DEFAULT GETDATE(),
    NOMBRE_CLIENTE VARCHAR(255) NOT NULL,
    TEL_CLIENTE VARCHAR(255) NOT NULL,
    TOTAL numeric(15,4),
    ID_EMPLEADO int NOT NULL,
    FOREIGN KEY (ID_EMPLEADO) REFERENCES USUARIOS(CODIGO_USUARIO)
);

   CREATE TABLE DETALLE_VENTA(
    CODIGO_DETALLE int NOT NULL IDENTITY (1,1) PRIMARY KEY,
    ID_VENTA int NOT NULL,
    ID_PRODUCTO int NOT NULL,
    CANTIDAD int,
    SUBTOTAL decimal(15,4),
    DET_VENCIMIENTO date,
    FOREIGN KEY (ID_VENTA) REFERENCES VENTA(CODIGO_VENTA),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(CODIGO_PRODUCTO)
); 

