----INSERT PERFIL
INSERT INTO PERFIL(DESCRIPCION)
VALUES ('ROOT'),('ADMINISTRADOR'),('EMPLEADO'),('TECNICO'),('SUPERVISOR');


----INSERT USUARIOS

INSERT INTO USUARIOS (USUARIO,NOMBRE,APELLIDO,CLAVE,FECHA_REGISTRO,CODIGO_PERFIL) 
VALUES ('NATANAEL','ESDRAS','ISMATUL','esd1234',GETDATE(),1),
       ('ERWIN','ERWIN','IXCAJOC','erw1234',GETDATE(),2),
       ('HILARIO','HILARIO','CHOXIN','yuc1234',GETDATE(),4),
       ('RAUL','RAUL','MURALLES','12345',GETDATE(),3)