-----insert Proveedores
INSERT INTO PROVEEDORES(NOMBRE_PROVEEDOR,TELEFONO,DIRECCION,CORREO)
VALUES('Distribuidora y Drogueria C&M','78305587','CIUDADA DE GUATEMALA','C&MDIS@gmail.com'),
      ('PHARMAR','56843221','GUATEMALA','PHARMARGT@hotmail.com'),
      ('CFE','56871132','GUATEMALA',''),
      ('MediAccess','00548750','USA',''),
      ('TecnMedic','78945612','GUATEMALA','')


----- insert Tipo de productos
INSERT INTO TIPO_PRODUCTO(TIP,DESCRIPCION)
VALUES('Comercial','Producto apto para su distribucion comercial'),
      ('Generico','....'),
      ('Industrial','....')

----- insert Laboratorios

INSERT INTO LABORATORIO(NOMBRE)
VALUES  ('GlucoHealth Meds'),
        ('AnticoagMed Ltd.'),
        ('AnticoagMed Ltd.'),
        ('PharmaCorp'),
        ('EyeCare Pharmaceuticals'),
        ('RespiraCare Pharmaceuticals'),
        ('AntiViralCare Inc.'),
        ('AntiViralCare Meds'),
        ('BioVit Pharma'),
        ('AntiParasit Tech'),
        ('BoneCare Inc.'),
        ('GoutSafe Pharma'),
        ('GoutFree Laboratories'),
        ('GoutFree Laboratories'),
        ('GoutControl Pharmaceuticals'),
        ('CalmMind Laboratories'),
        ('CalmMind Laboratories'),
        ('BioAntib Labs'),
        ('DiureticControl Pharmaceuticals'),
        ('HeartSupport Pharma'),
        ('NeuroPharma Inc.'),
        ('CardioBalance Labs'),
        ('CardioBalance Labs'),
        ('BioAntib Labs'),
        ('BioMed Pharmaceuticals'),
        ('BioMed Pharmaceuticals'),
        ('OncoCare Pharmaceuticals'),
        ('CardioWell Labs'),
        ('CardioMeds Ltd.'),
        ('CardioWell Labs'),
        ('CholesterolControl Ltd.'),
        ('ImmunoBalance Meds'),
        ('AntiBac Health'),
        ('AntiBac Health'),
        ('BioAntib Pharmaceuticals'),
        ('MuscleRelax Pharma'),
        ('RespiraPharm'),
        ('CardioMeds Ltd.'),
        ('NeuroPharma Inc.'),
        ('DermCare Pharmaceuticals'),
        ('SteroidHealth Co.'),
        ('SteroidHealth Co.'),
        ('OncoBalance Pharmaceuticals'),
        ('EyePharma Pharmaceuticals'),
        ('NeuroCare Pharmaceuticals'),
        ('CardioHealth Pharma'),
        ('CoughRelief Meds'),
        ('RespiraCare Meds'),
        ('RespiraCare Pharmaceuticals'),
        ('RespiraBalance Pharmaceuticals'),
        ('HormoBalance Labs'),
        ('BoneHealth Inc.'),
        ('HyperCare Pharmaceuticals'),
        ('HyperControl Pharmaceuticals'),
        ('HyperCare Pharmaceuticals'),
        ('HyperControl Meds'),
        ('NeuroStabil Pharma'),
        ('NeuroBalance Meds'),
        ('ThyroidBalance Inc.'),
        ('MuscleRelax Inc.'),
        ('CardioRelax Pharma'),
        ('CardioRelax Pharma'),
        ('Infection Control Labs'),
        ('Infection Control Labs'),
        ('BioAntib Labs'),
        ('BioAntib Pharmaceuticals'),
        ('InfectionControl Inc.'),
        ('PainControl Meds'),
        ('AllergyEase Meds'),
        ('AllergyEase Inc.'),
        ('AllergyRelief Pharmaceuticals'),
        ('AllergyEase Inc.'),
        ('OncoPharm Ltd.'),
        ('EyeCare Pharmaceuticals'),
        ('ImmunoPharm Ltd.'),
        ('ImmunoCare Pharmaceuticals'),
        ('NeuroBalance Pharmaceuticals'),
        ('BioAntib Labs'),
        ('BioAntib Labs'),
        ('BioAntib Pharma'),
        ('AntiInfective Pharmaceuticals'),
        ('BioAntib Pharmaceuticals'),
        ('BioAntib Pharmaceuticals'),
        ('DermCare Inc.'),
        ('CalmTech Pharmaceuticals'),
        ('CalmTech Pharmaceuticals'),
        ('CardioMeds Ltd.'),
        ('HyperControl Meds'),
        ('AnticoagTech'),
        ('AnticoagTech'),
        ('AnticoagTech'),
        ('AllergyRelief Meds'),
        ('AntisepticCare Meds'),
        ('DiureticCare Co.'),
        ('NeuroPharma Ltd.'),
        ('JointCare Pharmaceuticals'),
        ('GoutCare Inc.'),
        ('JointCare Pharmaceuticals'),
        ('GlucoCare Pharmaceuticals'),
        ('SkinCare Pharmaceuticals'),
        ('AllergyEase Meds'),
        ('AllergyControl Pharmaceuticals'),
        ('HormoControl Meds'),
        ('EarPharma Meds'),
        ('AntiInflamTech'),
        ('AntiInflamTech'),
        ('SteroidCare Pharmaceuticals'),
        ('Sedatec Pharma'),
        ('NeuroCalm Pharmaceuticals'),
        ('Sedatec Pharma'),
        ('PainRelief Pharmaceuticals'),
        ('PainFree Pharmaceuticals'),
        ('PainFree Pharmaceuticals'),
        ('PainRelief Meds'),
        ('BioAntib Labs'),
        ('AllergyCare Pharmaceuticals'),
        ('AllergyEase Meds'),
        ('HeartControl Meds'),
        ('HeartSupport Pharma'),
        ('HeartControl Meds'),
        ('CardioCare Pharmaceuticals'),
        ('CardioPharm Ltd.'),
        ('GutBalance Meds'),
        ('NeuroHealth Pharmaceuticals'),
        ('EyeCare Pharmaceuticals'),
        ('HyperWell Inc.'),
        ('BacterialControl Inc.'),
        ('BioAntib Pharmaceuticals'),
        ('BacterialControl Inc.'),
        ('NeuroBalance Meds'),
        ('HairHealth Pharmaceuticals'),
        ('GlucoHealth Pharmaceuticals'),
        ('CardioMeds Ltd.'),
        ('HyperMed Inc.'),
        ('AnticoagTech'),
        ('AntiViralTech Pharma'),
        ('CardioControl Pharma'),
        ('InfectionDefense Pharma'),
        ('NeuroPharma Meds'),
        ('CardioPharm Ltd.'),
        ('GastricCare Pharma'),
        ('GastricCare Pharma'),
        ('GutHealth Pharmaceuticals'),
        ('HormoBalance Meds'),
        ('PainRelief Pharmaceuticals'),
        ('PainControl Pharmaceuticals'),
        ('CholesterolCare Inc.'),
        ('GutRelief Pharmaceuticals'),
        ('CardioHealth Meds'),
        ('CholesterolCare Meds'),
        ('CholesterolControl Pharmaceuticals'),
        ('PainControl Pharma'),
        ('PainManagement Meds'),
        ('AllergyClear Meds'),
        ('AllergyClear Meds'),
        ('AllergyBalance Meds'),
        ('HairGrowth Ltd.'),
        ('AntiFungalCare Inc.'),
        ('NeuroBalance Pharmaceuticals'),
        ('MoodBalance Pharma'),
        ('NeuroBalance Pharmaceuticals'),
        ('MoodBalance Pharma'),
        ('RespiraCare Pharmaceuticals'),
        ('RespiraCare Meds'),
        ('CardioControl Pharma'),
        ('WaterControl Pharma'),
        ('WaterControl Pharma'),
        ('WaterControl Pharma'),
        ('NeuroBalance Pharmaceuticals'),
        ('NeuroHealth Pharmaceuticals'),
        ('NeuroPharma Ltd.'),
        ('CholesterolBalance Inc.'),
        ('GlucoControl Pharmaceuticals'),
        ('GlucoControl Meds'),
        ('GlucoHealth Inc.'),
        ('GlucoBalance Pharmaceuticals'),
        ('GlucoCare Ltd.'),
        ('AnticoagHealth Pharma'),
        ('HyperCare Pharma'),
        ('BloodPressureCare Co.'),
        ('DiureticHealth Ltd.'),
        ('DiureticHealth Ltd.'),
        ('HyperBalance Pharmaceuticals'),
        ('ImmunoTech Inc.'),
        ('ImmunityPharm'),
        ('ImmunityPharm'),
        ('AllergyRelief Pharmaceuticals'),
        ('CalmTech Laboratories'),
        ('BoneHealth Meds'),
        ('MedHealth Laboratories'),
        ('MedHealth Laboratories'),
        ('OncoCare Pharmaceuticals'),
        ('DiureticTech Ltd.'),
        ('DiureticHealth Pharma'),
        ('Diabetech Pharmaceuticals'),
        ('GlucoTech Pharmaceuticals'),
        ('RespiraPharma Ltd.'),
        ('HyperWell Pharmaceuticals'),
        ('OncoBalance Pharmaceuticals'),
        ('SkinCare Pharmaceuticals'),
        ('AntiFungalCare Inc.'),
        ('HeartWell Pharmaceuticals'),
        ('PainControl Pharmaceuticals'),
        ('CardioBalance Meds'),
        ('NeuroStabil Meds'),
        ('GutRelief Co.'),
        ('NeuroControl Pharma'),
        ('EyeHealth Meds'),
        ('EyeCare Pharmaceuticals'),
        ('AllergyControl Meds'),
        ('BioAntib Pharmaceuticals'),
        ('BioAntib Pharma'),
        ('ThyroidCare Co.'),
        ('ThyroidCare Pharmaceuticals'),
        ('ThyroidCare Co.'),
        ('GlucoControl Ltd.'),
        ('InfectionDefense Pharmaceuticals'),
        ('InfectionControl Meds'),
        ('GlucoHealth Meds'),
        ('GlucoBalance Pharmaceuticals'),
        ('ACEInhib Labs'),
        ('CardioHealth Ltd.'),
        ('ACEInhib Labs'),
        ('Allergy Relief Meds'),
        ('AllergyEase Pharmaceuticals'),
        ('Allergy Relief Meds'),
        ('TranquilCo Labs'),
        ('TranquilCo Labs'),
        ('CardioBalance Pharmaceuticals'),
        ('CardioMeds Ltd.'),
        ('CardioMeds Ltd.'),
        ('NeuroCare Pharmaceuticals'),
        ('ParasitControl Inc.'),
        ('AntiParasit Tech'),
        ('SleepWell Pharmaceuticals'),
        ('PainRelief Meds'),
        ('NeuroBalance Inc.'),
        ('InfectionDefense Pharma'),
        ('BioAntib Pharmaceuticals'),
        ('GlucoLife Inc.'),
        ('GlucoLife Inc.'),
        ('SteroidCare Pharmaceuticals'),
        ('GutRelief Inc.'),
        ('GutRelief Inc.'),
        ('InfectionSafe Co.'),
        ('InfectionSafe Co.'),
        ('AntiInfective Pharma'),
        ('NeuroCalm Pharmaceuticals'),
        ('UroBalance Inc.'),
        ('NeuroBalance Pharmaceuticals'),
        ('DermCare Pharmaceuticals'),
        ('RespiraTech Inc.'),
        ('RespiraCare Pharmaceuticals'),
        ('BioAntib Pharmaceuticals'),
        ('AntiOpioid Pharmaceuticals'),
        ('PainRelief Co.'),
        ('PainControl Meds'),
        ('PainRelief Co.'),
        ('CardioPharma Meds'),
        ('CardioRelax Meds'),
        ('HyperWell Meds'),
        ('AntiParasit Pharmaceuticals'),
        ('AntiParasit Pharmaceuticals'),
        ('HeartSupport Ltd.'),
        ('BioAntib Pharmaceuticals'),
        ('NeuroHealth Meds'),
        ('HyperControl Pharmaceuticals'),
        ('EyeCare Pharmaceuticals'),
        ('ImmunoBalance Pharmaceuticals'),
        ('Stomach Health Co.'),
        ('Stomach Health Co.'),
        ('NeuroBalance Pharmaceuticals'),
        ('UroBalance Pharmaceuticals'),
        ('UroControl Pharmaceuticals'),
        ('PharmaCorp'),
        ('PainRelief Pharmaceuticals'),
        ('VascularCare Pharmaceuticals'),
        ('HyperMed Pharmaceuticals'),
        ('RespiratoryHealth Pharmaceuticals'),
        ('SteroidCare Inc.'),
        ('SteroidCare Pharmaceuticals'),
        ('SteroidCare Inc.'),
        ('HyperMed Pharmaceuticals'),
        ('HyperMed Pharmaceuticals'),
        ('AcidRelief Pharma'),
        ('GutBalance Meds'),
        ('AcidRelief Pharma'),
        ('NeuroPharma Ltd.'),
        ('AnticoagMed Ltd.'),
        ('CholesterolClear Inc.'),
        ('HeartCare Pharma'),
        ('HeartCare Pharma'),
        ('ProstateCare Inc.'),
        ('PainControl Pharmaceuticals'),
        ('PainControl Pharmaceuticals'),
        ('BloodPressure Inc.'),
        ('BloodPressure Inc.'),
        ('CardioSupport Inc.'),
        ('CardioSupport Inc.'),
        ('BloodBalance Pharmaceuticals'),
        ('BloodBalance Pharmaceuticals')
